name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy=2.5.1
  - pandas=2.3.3
  - pytest=9.1.1
  - scipy=1.18.0
  - pip=26.2.1
  - pip:
      - mlflow==3.13.0
      - wandb==0.28.1
