name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=26.2.1
  - requests=2.34.2
  - scikit-learn=1.9.0
  - pandas=2.3.3
  - pip:
      - mlflow==3.13.0
      - wandb==0.28.1
      - -e ..
